[package]
name = "LocationHelper"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] } 
warp = { version = "0.4.2", features = ["server"] }
chrono = "0.4.42"
local-ip-address = "0.6.7"
btleplug = "0.11.8"
serde_json = "1.0.145"
reqwest = { version = "0.12", features = ["json", "blocking", "rustls-tls"] }
regex = "1.12.2"
once_cell = "1.21.3"
